### PR TITLE
New signal-to-noise ratio for prices

### PR DESCRIPTION
**Pull request by peterccarl**
Here's a function for examining trendiness over a timeframe using ATR as a proxy for volatility.  I think this fits the package, but let me know if you think it goes elsewhere. pcc

### CODE REVIEW

**Comment by braverock** [comment]
This may reopen the conversation about moving the OHLC functionality 'upstream' from quantmod to TTR.

This pull request can't be merged as is, because quantmod requires TTR, so this creates a circular dependency.  

Also, CRAN only wants you to check and require another package if that package is in Suggests.  otherwise they want you to have either put it in Requires or Imports

**Comment by peterccarl** [comment]
Sorry, I'll remove those lines since they are unnecessary if the function
is in ttr.  Good catch.

**Comment by joshuaulrich** [comment]
Some other items:
1. `...` are not passed to `ATR` as documented.
2. The `try.xts` / `reclass` paradigm should be used so all time series classes will be supported.  See other functions for examples.
3. `lag.xts` should be called explicitly in case `try.xts` fails and `HLC` is a matrix.

**Comment by peterccarl** [comment]
Fixed, thanks for the pointers.

**Comment by joshuaulrich** [comment]
`reclass` isn't called before `return` and `quantmod::Cl` still creates a circular dependency.

**Comment by peterccarl** [comment]
Ok, I missed the real circularity you were referring to.  I've removed it.

**Comment by joshuaulrich** [comment]
Merged via 990da831c44785fb3043936597cc0fae4cd42444.

**Pull request closed without merging**
